
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL1-PC15
 */
public class NewJFrameq extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameq
     */
    public NewJFrameq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtplayer1 = new javax.swing.JTextField();
        txtplayer2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PLAYER1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PLAYER2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 81, -1, -1));
        getContentPane().add(txtplayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));
        getContentPane().add(txtplayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ROCK/PAPER/SCISSORS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 210, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel5.setText("[1]ROCK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel6.setText("[2]PAPER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel7.setText("[3]SCISSORS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int player1 = Integer.parseInt(txtplayer1.getText());
       int player2 = Integer.parseInt(txtplayer2.getText());
      
       
       
       if (player1 == 1 && player2 == 1)
        {
            JOptionPane.showConfirmDialog(null, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 1 && player2 == 2)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 2 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 1 && player2 == 3)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 1 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 2 && player2 == 1)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 1 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 2 && player2 == 2)
        {
            JOptionPane.showConfirmDialog(null, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 2 && player2 == 3)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 2 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 3 && player2 == 1)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 1 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 3 && player2 == 2)
        {
            JOptionPane.showConfirmDialog(null, "PLAYER 2 WINS", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (player1 == 3 && player2 == 3)
        {
            JOptionPane.showConfirmDialog(null, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
            JOptionPane.showConfirmDialog(null, "INCORRECT INPUT!", "RPS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtplayer1;
    private javax.swing.JTextField txtplayer2;
    // End of variables declaration//GEN-END:variables
}
